package cm.uds.fuchsia.gag.model.configuration;

import cm.uds.fuchsia.gag.model.specification.Parameter;
import cm.uds.fuchsia.gag.util.EncapsulatedValue;
import cm.uds.fuchsia.gag.util.NameGenerator;

public class Data {
	private Object value;
	private Parameter parameter;
	
	private String name ;//generated by the name generator

	public Data() {
		name=NameGenerator.newName();
	}
	public Data(Boolean setCounter) {
		if(setCounter)name=NameGenerator.newName();
	}
	public Object getValue() {
		return value;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	public Parameter getParameter() {
		return parameter;
	}
	
	public void setParameter(Parameter parameter) {
		this.parameter = parameter;
	}

	public String getName() {
		return name;
	}
	public Data clone(){
		Data d= new Data(false);
		d.name=name;
		d.parameter=parameter;
		d.value = value;
		if(value instanceof EncapsulatedValue){
			EncapsulatedValue ecVal = ((EncapsulatedValue) value).clone();
			ecVal.setContainerRef(d);
			d.value= ecVal;
		}
		return d;
	}

/*
	public void setName(String name) {
		this.name = name;
	}
*/	
	

}
